// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';

// github.com/benoitkugler/atable/sql/sejours.Date
typedef Date = DateTime;

// github.com/benoitkugler/atable/sql/sejours.IdMeal
typedef IdMeal = int;
