// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';
import 'stdlib_github.com_benoitkugler_atable_sql_menus.dart';
import 'stdlib_github.com_benoitkugler_atable_sql_sejours.dart';

// github.com/benoitkugler/atable/controllers/shop-session.CreateSessionOut
class CreateSessionOut {
  final String sessionID;

  const CreateSessionOut(this.sessionID);

  @override
  String toString() {
    return "CreateSessionOut($sessionID)";
  }
}

CreateSessionOut createSessionOutFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return CreateSessionOut(stringFromJson(json['SessionID']));
}

Map<String, dynamic> createSessionOutToJson(CreateSessionOut item) {
  return {"SessionID": stringToJson(item.sessionID)};
}

// github.com/benoitkugler/atable/controllers/shop-session.IngredientUses
class IngredientUses {
  final Ingredient ingredient;
  final List<Quantite> quantites;
  final bool checked;

  const IngredientUses(this.ingredient, this.quantites, this.checked);

  @override
  String toString() {
    return "IngredientUses($ingredient, $quantites, $checked)";
  }
}

IngredientUses ingredientUsesFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return IngredientUses(ingredientFromJson(json['Ingredient']),
      listQuantiteFromJson(json['Quantites']), boolFromJson(json['Checked']));
}

Map<String, dynamic> ingredientUsesToJson(IngredientUses item) {
  return {
    "Ingredient": ingredientToJson(item.ingredient),
    "Quantites": listQuantiteToJson(item.quantites),
    "Checked": boolToJson(item.checked)
  };
}

/// github.com/benoitkugler/atable/controllers/shop-session.Origin
abstract class Origin {}

Origin originFromJson(dynamic json_) {
  final json = json_ as Map<String, dynamic>;
  final kind = json['Kind'] as String;
  final data = json['Data'];
  switch (kind) {
    case "OriginMeal":
      return originMealFromJson(data);
    case "OriginStock":
      return originStockFromJson(data);
    default:
      throw ("unexpected type");
  }
}

Map<String, dynamic> originToJson(Origin item) {
  if (item is OriginMeal) {
    return {'Kind': "OriginMeal", 'Data': originMealToJson(item)};
  } else if (item is OriginStock) {
    return {'Kind': "OriginStock", 'Data': originStockToJson(item)};
  } else {
    throw ("unexpected type");
  }
}

// github.com/benoitkugler/atable/controllers/shop-session.OriginMeal
class OriginMeal implements Origin {
  final Date mealDate;
  final Horaire mealHoraire;
  final List<String> groupes;
  final String receipeName;

  const OriginMeal(
      this.mealDate, this.mealHoraire, this.groupes, this.receipeName);

  @override
  String toString() {
    return "OriginMeal($mealDate, $mealHoraire, $groupes, $receipeName)";
  }
}

OriginMeal originMealFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return OriginMeal(
      dateTimeFromJson(json['MealDate']),
      horaireFromJson(json['MealHoraire']),
      listStringFromJson(json['Groupes']),
      stringFromJson(json['ReceipeName']));
}

Map<String, dynamic> originMealToJson(OriginMeal item) {
  return {
    "MealDate": dateTimeToJson(item.mealDate),
    "MealHoraire": horaireToJson(item.mealHoraire),
    "Groupes": listStringToJson(item.groupes),
    "ReceipeName": stringToJson(item.receipeName)
  };
}

// github.com/benoitkugler/atable/controllers/shop-session.OriginStock
class OriginStock implements Origin {
  const OriginStock();

  @override
  String toString() {
    return "OriginStock()";
  }
}

OriginStock originStockFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return OriginStock();
}

Map<String, dynamic> originStockToJson(OriginStock item) {
  return {};
}

// github.com/benoitkugler/atable/controllers/shop-session.Quantite
class Quantite {
  final double quantite;
  final Unite unite;
  final Origin origin;

  const Quantite(this.quantite, this.unite, this.origin);

  @override
  String toString() {
    return "Quantite($quantite, $unite, $origin)";
  }
}

Quantite quantiteFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return Quantite(doubleFromJson(json['Quantite']),
      uniteFromJson(json['Unite']), originFromJson(json['Origin']));
}

Map<String, dynamic> quantiteToJson(Quantite item) {
  return {
    "Quantite": doubleToJson(item.quantite),
    "Unite": uniteToJson(item.unite),
    "Origin": originToJson(item.origin)
  };
}

// github.com/benoitkugler/atable/controllers/shop-session.Session
class Session {
  final String id;
  final ShopList list;

  const Session(this.id, this.list);

  @override
  String toString() {
    return "Session($id, $list)";
  }
}

Session sessionFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return Session(stringFromJson(json['Id']), shopListFromJson(json['List']));
}

Map<String, dynamic> sessionToJson(Session item) {
  return {"Id": stringToJson(item.id), "List": shopListToJson(item.list)};
}

// github.com/benoitkugler/atable/controllers/shop-session.ShopList
typedef ShopList = List<IngredientUses>;

ShopList shopListFromJson(dynamic json) {
  return listIngredientUsesFromJson(json);
}

dynamic shopListToJson(ShopList item) {
  return listIngredientUsesToJson(item);
}

// github.com/benoitkugler/atable/controllers/shop-session.UpdateSessionIn
class UpdateSessionIn {
  final IdIngredient id;
  final bool checked;

  const UpdateSessionIn(this.id, this.checked);

  @override
  String toString() {
    return "UpdateSessionIn($id, $checked)";
  }
}

UpdateSessionIn updateSessionInFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return UpdateSessionIn(
      intFromJson(json['Id']), boolFromJson(json['Checked']));
}

Map<String, dynamic> updateSessionInToJson(UpdateSessionIn item) {
  return {"Id": intToJson(item.id), "Checked": boolToJson(item.checked)};
}

List<IngredientUses> listIngredientUsesFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(ingredientUsesFromJson).toList();
}

List<dynamic> listIngredientUsesToJson(List<IngredientUses> item) {
  return item.map(ingredientUsesToJson).toList();
}

List<Quantite> listQuantiteFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(quantiteFromJson).toList();
}

List<dynamic> listQuantiteToJson(List<Quantite> item) {
  return item.map(quantiteToJson).toList();
}

List<String> listStringFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(stringFromJson).toList();
}

List<dynamic> listStringToJson(List<String> item) {
  return item.map(stringToJson).toList();
}
