// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';
import 'stdlib_github.com_benoitkugler_atable_sql_menus.dart';
import 'stdlib_github.com_benoitkugler_atable_sql_sejours.dart';

// github.com/benoitkugler/atable/controllers/shop-session.IngredientUses
class IngredientUses {
  final Ingredient ingredient;
  final List<Quantite> quantites;
  final bool checked;

  const IngredientUses(this.ingredient, this.quantites, this.checked);

  @override
  String toString() {
    return "IngredientUses($ingredient, $quantites, $checked)";
  }
}

IngredientUses ingredientUsesFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return IngredientUses(ingredientFromJson(json['Ingredient']),
      listQuantiteFromJson(json['Quantites']), boolFromJson(json['Checked']));
}

Map<String, dynamic> ingredientUsesToJson(IngredientUses item) {
  return {
    "Ingredient": ingredientToJson(item.ingredient),
    "Quantites": listQuantiteToJson(item.quantites),
    "Checked": boolToJson(item.checked)
  };
}

// github.com/benoitkugler/atable/controllers/shop-session.Origin
class Origin {
  final Date mealDate;
  final String mealName;
  final String receipeName;

  const Origin(this.mealDate, this.mealName, this.receipeName);

  @override
  String toString() {
    return "Origin($mealDate, $mealName, $receipeName)";
  }
}

Origin originFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return Origin(dateTimeFromJson(json['MealDate']),
      stringFromJson(json['MealName']), stringFromJson(json['ReceipeName']));
}

Map<String, dynamic> originToJson(Origin item) {
  return {
    "MealDate": dateTimeToJson(item.mealDate),
    "MealName": stringToJson(item.mealName),
    "ReceipeName": stringToJson(item.receipeName)
  };
}

// github.com/benoitkugler/atable/controllers/shop-session.Quantite
class Quantite {
  final double quantite;
  final Unite unite;
  final Origin origin;

  const Quantite(this.quantite, this.unite, this.origin);

  @override
  String toString() {
    return "Quantite($quantite, $unite, $origin)";
  }
}

Quantite quantiteFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return Quantite(doubleFromJson(json['Quantite']),
      uniteFromJson(json['Unite']), originFromJson(json['Origin']));
}

Map<String, dynamic> quantiteToJson(Quantite item) {
  return {
    "Quantite": doubleToJson(item.quantite),
    "Unite": uniteToJson(item.unite),
    "Origin": originToJson(item.origin)
  };
}

// github.com/benoitkugler/atable/controllers/shop-session.Session
class Session {
  final String id;
  final ShopList list;

  const Session(this.id, this.list);

  @override
  String toString() {
    return "Session($id, $list)";
  }
}

Session sessionFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return Session(stringFromJson(json['Id']), shopListFromJson(json['List']));
}

Map<String, dynamic> sessionToJson(Session item) {
  return {"Id": stringToJson(item.id), "List": shopListToJson(item.list)};
}

// github.com/benoitkugler/atable/controllers/shop-session.ShopList
typedef ShopList = List<IngredientUses>;

ShopList shopListFromJson(dynamic json) {
  return listIngredientUsesFromJson(json);
}

dynamic shopListToJson(ShopList item) {
  return listIngredientUsesToJson(item);
}

List<IngredientUses> listIngredientUsesFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(ingredientUsesFromJson).toList();
}

List<dynamic> listIngredientUsesToJson(List<IngredientUses> item) {
  return item.map(ingredientUsesToJson).toList();
}

List<Quantite> listQuantiteFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(quantiteFromJson).toList();
}

List<dynamic> listQuantiteToJson(List<Quantite> item) {
  return item.map(quantiteToJson).toList();
}
