// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';
import 'stdlib_github.com_benoitkugler_atable_sql_menus.dart';
import 'stdlib_github.com_benoitkugler_atable_sql_sejours.dart';

// github.com/benoitkugler/atable/controllers/sejours.MealM
class MealM {
  final IdMeal id;
  final IdMenu idMenu;
  final String name;
  final Date date;
  final int for_;

  const MealM(this.id, this.idMenu, this.name, this.date, this.for_);

  @override
  String toString() {
    return "MealM($id, $idMenu, $name, $date, $for_)";
  }
}

MealM mealMFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return MealM(
      intFromJson(json['Id']),
      intFromJson(json['IdMenu']),
      stringFromJson(json['Name']),
      dateTimeFromJson(json['Date']),
      intFromJson(json['For_']));
}

Map<String, dynamic> mealMToJson(MealM item) {
  return {
    "Id": intToJson(item.id),
    "IdMenu": intToJson(item.idMenu),
    "Name": stringToJson(item.name),
    "Date": dateTimeToJson(item.date),
    "For_": intToJson(item.for_)
  };
}

// github.com/benoitkugler/atable/controllers/sejours.TablesM
class TablesM {
  final List<Ingredient> ingredients;
  final List<Receipe> receipes;
  final ReceipeIngredients receipeIngredients;
  final List<Menu> menus;
  final MenuReceipes menuReceipes;
  final MenuIngredients menuIngredients;
  final List<MealM> meals;

  const TablesM(this.ingredients, this.receipes, this.receipeIngredients,
      this.menus, this.menuReceipes, this.menuIngredients, this.meals);

  @override
  String toString() {
    return "TablesM($ingredients, $receipes, $receipeIngredients, $menus, $menuReceipes, $menuIngredients, $meals)";
  }
}

TablesM tablesMFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return TablesM(
      listIngredientFromJson(json['Ingredients']),
      listReceipeFromJson(json['Receipes']),
      receipeIngredientsFromJson(json['ReceipeIngredients']),
      listMenuFromJson(json['Menus']),
      menuReceipesFromJson(json['MenuReceipes']),
      menuIngredientsFromJson(json['MenuIngredients']),
      listMealMFromJson(json['Meals']));
}

Map<String, dynamic> tablesMToJson(TablesM item) {
  return {
    "Ingredients": listIngredientToJson(item.ingredients),
    "Receipes": listReceipeToJson(item.receipes),
    "ReceipeIngredients": receipeIngredientsToJson(item.receipeIngredients),
    "Menus": listMenuToJson(item.menus),
    "MenuReceipes": menuReceipesToJson(item.menuReceipes),
    "MenuIngredients": menuIngredientsToJson(item.menuIngredients),
    "Meals": listMealMToJson(item.meals)
  };
}

List<Ingredient> listIngredientFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(ingredientFromJson).toList();
}

List<dynamic> listIngredientToJson(List<Ingredient> item) {
  return item.map(ingredientToJson).toList();
}

List<MealM> listMealMFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(mealMFromJson).toList();
}

List<dynamic> listMealMToJson(List<MealM> item) {
  return item.map(mealMToJson).toList();
}

List<Menu> listMenuFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(menuFromJson).toList();
}

List<dynamic> listMenuToJson(List<Menu> item) {
  return item.map(menuToJson).toList();
}

List<Receipe> listReceipeFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(receipeFromJson).toList();
}

List<dynamic> listReceipeToJson(List<Receipe> item) {
  return item.map(receipeToJson).toList();
}
