package sejours

import (
	"math/rand"
	"time"

	"github.com/benoitkugler/atable/sql/menus"
	"github.com/benoitkugler/atable/sql/orders"
	"github.com/benoitkugler/atable/sql/users"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randDate() Date {
	return Date(randtTime())
}

func randGroup() Group {
	var s Group
	s.Id = randIdGroup()
	s.Sejour = randIdSejour()
	s.Name = randstring()
	s.Color = randstring()
	s.Size = randint()

	return s
}

func randHoraire() Horaire {
	choix := [...]Horaire{PetitDejeuner, Midi, Gouter, Diner, Cinquieme}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randIdGroup() IdGroup {
	return IdGroup(randint64())
}

func randIdMeal() IdMeal {
	return IdMeal(randint64())
}

func randIdSejour() IdSejour {
	return IdSejour(randint64())
}

func randMeal() Meal {
	var s Meal
	s.Id = randIdMeal()
	s.Sejour = randIdSejour()
	s.Menu = randmen_IdMenu()
	s.Jour = randint()
	s.AdditionalPeople = randint()
	s.Horaire = randHoraire()

	return s
}

func randMealGroup() MealGroup {
	var s MealGroup
	s.IdMeal = randIdMeal()
	s.IdGroup = randIdGroup()

	return s
}

func randOptionnalIdProfile() OptionnalIdProfile {
	var s OptionnalIdProfile
	s.Valid = randbool()
	s.IdProfile = randord_IdProfile()

	return s
}

func randSejour() Sejour {
	var s Sejour
	s.Id = randIdSejour()
	s.Owner = randuse_IdUser()
	s.Start = randDate()
	s.Name = randstring()
	s.IdProfile = randOptionnalIdProfile()

	return s
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randmen_IdMenu() menus.IdMenu {
	return menus.IdMenu(randint64())
}

func randord_IdProfile() orders.IdProfile {
	return orders.IdProfile(randint64())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}

func randuse_IdUser() users.IdUser {
	return users.IdUser(randint64())
}
