package orders

import (
	"math/rand"

	"github.com/benoitkugler/atable/sql/menus"
	"github.com/benoitkugler/atable/sql/users"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randIdProfile() IdProfile {
	return IdProfile(randint64())
}

func randIdSupplier() IdSupplier {
	return IdSupplier(randint64())
}

func randIngredientSupplier() IngredientSupplier {
	var s IngredientSupplier
	s.IdIngredient = randmen_IdIngredient()
	s.IdSupplier = randIdSupplier()
	s.IdProfile = randIdProfile()

	return s
}

func randIngredientkindSupplier() IngredientkindSupplier {
	var s IngredientkindSupplier
	s.Kind = randmen_IngredientKind()
	s.IdSupplier = randIdSupplier()
	s.IdProfile = randIdProfile()

	return s
}

func randProfile() Profile {
	var s Profile
	s.Id = randIdProfile()
	s.IdOwner = randuse_IdUser()
	s.Name = randstring()

	return s
}

func randSupplier() Supplier {
	var s Supplier
	s.Id = randIdSupplier()
	s.IdProfile = randIdProfile()
	s.Name = randstring()

	return s
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randmen_IdIngredient() menus.IdIngredient {
	return menus.IdIngredient(randint64())
}

func randmen_IngredientKind() menus.IngredientKind {
	choix := [...]menus.IngredientKind{menus.I_Empty, menus.I_Legumes, menus.I_Feculents, menus.I_Viandes, menus.I_Epicerie, menus.I_Laitages, menus.I_Boulangerie}
	i := rand.Intn(len(choix))
	return choix[i]
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randuse_IdUser() users.IdUser {
	return users.IdUser(randint64())
}
