package shopsession

import (
	"encoding/json"

	"github.com/benoitkugler/atable/sql/menus"
)

// Code generated by gomacro/generator/gounions. DO NOT EDIT

// OriginWrapper may be used as replacements for Origin
// when working with JSON
type OriginWrapper struct {
	Data Origin
}

func (out *OriginWrapper) UnmarshalJSON(src []byte) error {
	var wr struct {
		Kind string
		Data json.RawMessage
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	switch wr.Kind {
	case "OriginMeal":
		var data OriginMeal
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case "OriginStock":
		var data OriginStock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data

	default:
		panic("exhaustive switch")
	}
	return err
}

func (item OriginWrapper) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Data any
		Kind string
	}
	var wr wrapper
	switch data := item.Data.(type) {
	case OriginMeal:
		wr = wrapper{Kind: "OriginMeal", Data: data}
	case OriginStock:
		wr = wrapper{Kind: "OriginStock", Data: data}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}

const (
	OriginMealOrKind  = "OriginMeal"
	OriginStockOrKind = "OriginStock"
)

func (item Quantite) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Quantite float64
		Unite    menus.Unite
		Origin   OriginWrapper
	}
	wr := wrapper{
		Quantite: item.Quantite,
		Unite:    item.Unite,
		Origin:   OriginWrapper{item.Origin},
	}
	return json.Marshal(wr)
}

func (item *Quantite) UnmarshalJSON(src []byte) error {
	type wrapper struct {
		Quantite float64
		Unite    menus.Unite
		Origin   OriginWrapper
	}
	var wr wrapper
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	item.Quantite = wr.Quantite
	item.Unite = wr.Unite
	item.Origin = wr.Origin.Data
	return nil
}
